Sprint 04
AndreyFedin/MovieQuiz-ios pull request #2
Opened 2022-11-16 14:09 UTC by AndreyFedin

2022-11-16 18:48 UTC, mmbabaev commented
<img width="522" alt="Screen Shot 2022-11-16 at 21 46 00" src="https://user-images.githubusercontent.com/12600807/202266650-8cedd4de-d678-4aad-b2f3-96ff235fc6db.png">
Замечания по верстке: 
1) Цвет background должен быть не системный Black Color, а Black из добавленных в проект цветов
2) Нет округления у картинки и обводки ответа (cornerRadius)
3) Не хватает bottom constraint к safe area с constant = 0

2022-11-16 18:56 UTC, mmbabaev requested changes

2022-11-16 18:56 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) { // запускаем задачу через 1 секунду
Если быстро нажимать одну и ту же кнопку, то срабатывают лишние нажатия, пока мы ожидаем следующего вопроса. Чтобы этого не было, можно использовать свойство isEnabled. При начале ожидания "выключать" кнопку, после ожидания "включать" https://developer.apple.com/documentation/uikit/uicontrol/1618217-isenabled

2022-11-16 18:56 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBAction private func ButtonYesDidTap(_ sender: Any) {
принято называть функции с маленькой буквы

2022-11-16 18:56 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBAction private func ButtonYesDidTap(_ sender: Any) {
+ `yesButtonDidTap`

2022-11-16 18:56 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet private var ButtonNo: UIButton!
почему именно кнопки с большой? Давайте тоже их с маленькой. 
И правильнее будет `noButton`

2022-11-16 18:56 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        // здесь мы показываем результат прохождения квиза
предлагаю удалить обучающие комментарии

2022-11-17 15:12 UTC, AndreyFedin commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBAction private func ButtonYesDidTap(_ sender: Any) {
исправил

2022-11-17 15:12 UTC, AndreyFedin commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet private var ButtonNo: UIButton!
исправил

2022-11-17 15:12 UTC, AndreyFedin commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        // здесь мы показываем результат прохождения квиза
исправил

2022-11-26 14:52 UTC, merged