Sprint 07
AndreyFedin/MovieQuiz-ios pull request #5
Opened 2023-01-02 12:23 UTC by AndreyFedin

2023-01-06 08:08 UTC, IBDesignable commented on MovieQuizTests/MovieQuizPresenterTests.swift
> +        let sut = MovieQuizPresenter(viewController: viewControllerMock)
здесь инициализатор ожидает MovieQuizViewController и тип MovieQuizViewControllerProtocolMock не подходит, тесты не компилируются

2023-01-06 08:15 UTC, IBDesignable requested changes

2023-01-06 08:15 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    }
в идеале, на Presenter не должно остаться сущностей из UIKit (UIAlertController). Просто представь, что логику приложения осуществляет презентер, а вью контроллер может являться как приложением для терминала, так и интерфейсом для приложения под macOS. UIKit фреймворк для iOS и если его сущности останутся в слое логики, то такой гипкости не достичь. 

Поэтому предлагаю алерт презентер и этот метод перенести обратно во вью контроллер (ничего страшного, если вью контроллер будет держать ссылки на несколько презентеров – это не нарушает архитектуру MVP)

2023-01-06 08:15 UTC, IBDesignable commented on MovieQuizUITests/MovieQuizUITestsLaunchTests.swift
> +final class MovieQuizUITestsLaunchTests: XCTestCase {
тест ничего полезного не несет, давай удалять такое

2023-01-06 08:15 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    }
в презентере можно оставить дополнительную связь с контроллером методом showAlert если угодно

2023-01-06 20:17 UTC, AndreyFedin commented on MovieQuizTests/MovieQuizPresenterTests.swift
> +        let sut = MovieQuizPresenter(viewController: viewControllerMock)
ага я так и понял, так как и начал с того, что передал MovieQuizViewController. Удалил все лишнее теперь тест прошел

2023-01-06 20:17 UTC, AndreyFedin commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    }
перенес

2023-01-06 20:33 UTC, AndreyFedin commented on MovieQuizUITests/MovieQuizUITestsLaunchTests.swift
> +final class MovieQuizUITestsLaunchTests: XCTestCase {
Саш, странно у меня в репе нет этого файла

2023-01-08 18:41 UTC, IBDesignable commented on MovieQuizUITests/MovieQuizUITestsLaunchTests.swift
> +final class MovieQuizUITestsLaunchTests: XCTestCase {
в репозитории то как раз есть, а в структуре проекта Xcode его нет. Так происходит когда в Xcode удаляешь файл только как Reference, надо удалять в корзину
![Uploading Снимок экрана 2023-01-08 в 20.40.41.png…]()

сейчас открой проект в Finder, MovieQuizUITests/MovieQuizUITestsLaunchTests.swift и удали руками.

2023-01-08 18:49 UTC, IBDesignable commented on MovieQuizTests/MovieQuizPresenterTests.swift
> +        let sut = MovieQuizPresenter(viewController: viewControllerMock)
Тест конечно проходит, но с точки зрения MVP тема до конца не разобрана. 

Было правильно использовать `MovieQuizViewControllerProtocol` в ините презентера. Сохранить нужно было ссылку именно по протоколу (также мы делали для сервиса статистики). 
Таким образом ты даешь гибкость презентеру – он сможет принимать в себя как `MovieQuizViewController`, так и `MovieQuizViewControllerProtocolMock`, но чтобы это "заработало" необходимо протокол "поддержать" обеим сущностям (то есть удовлетворить протоколу) и `MovieQuizViewController`, и `MovieQuizViewControllerProtocolMock`


и небольшая заметка: MovieQuizViewControllerProtocolMock — протокол в названии лишний)

с точки зрения рефакторинга на MVP – это недоработанный кусок кода, который нужно доработать.

2023-01-08 18:54 UTC, IBDesignable requested changes

2023-01-08 18:54 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>          noButton.isEnabled = false
маловато одну кнопку блочить, я же могу вторым пальцем противоположную кнопку тыкать

2023-01-09 06:10 UTC, AndreyFedin commented on MovieQuizUITests/MovieQuizUITestsLaunchTests.swift
> +final class MovieQuizUITestsLaunchTests: XCTestCase {
о, да, действительно есть, удалил

2023-01-09 10:55 UTC, AndreyFedin commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>          noButton.isEnabled = false
исправил

2023-01-09 12:46 UTC, AndreyFedin commented on MovieQuizTests/MovieQuizPresenterTests.swift
> +        let sut = MovieQuizPresenter(viewController: viewControllerMock)
исправил

2023-01-09 21:45 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +    private let questionsAmount: Int = 3
Эть, не по ТЗ, верти обратно

2023-01-09 21:45 UTC, IBDesignable commented on MovieQuiz/Presentation/MovieQuizPresenter.swift
> +            print(alertModel)
тоже лишний, давай удалять

2023-01-30 16:42 UTC, merged